# automatically generated by the FlatBuffers compiler, do not modify

# namespace: TensorProto_

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Segment(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Segment()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSegment(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Segment
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Segment
    def Begin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Segment
    def End(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def SegmentStart(builder):
    builder.StartObject(2)

def Start(builder):
    SegmentStart(builder)

def SegmentAddBegin(builder, begin):
    builder.PrependInt64Slot(0, begin, 0)

def AddBegin(builder, begin):
    SegmentAddBegin(builder, begin)

def SegmentAddEnd(builder, end):
    builder.PrependInt64Slot(1, end, 0)

def AddEnd(builder, end):
    SegmentAddEnd(builder, end)

def SegmentEnd(builder):
    return builder.EndObject()

def End(builder):
    return SegmentEnd(builder)


class SegmentT(object):

    # SegmentT
    def __init__(self):
        self.begin = 0  # type: int
        self.end = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        segment = Segment()
        segment.Init(buf, pos)
        return cls.InitFromObj(segment)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, segment):
        x = SegmentT()
        x._UnPack(segment)
        return x

    # SegmentT
    def _UnPack(self, segment):
        if segment is None:
            return
        self.begin = segment.Begin()
        self.end = segment.End()

    # SegmentT
    def Pack(self, builder):
        SegmentStart(builder)
        SegmentAddBegin(builder, self.begin)
        SegmentAddEnd(builder, self.end)
        segment = SegmentEnd(builder)
        return segment
