# automatically generated by the FlatBuffers compiler, do not modify

# namespace: TypeProto_

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Optional(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Optional()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOptional(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Optional
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Optional
    def ElemType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from onnx.TypeProto import TypeProto
            obj = TypeProto()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def OptionalStart(builder):
    builder.StartObject(1)

def Start(builder):
    OptionalStart(builder)

def OptionalAddElemType(builder, elemType):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(elemType), 0)

def AddElemType(builder, elemType):
    OptionalAddElemType(builder, elemType)

def OptionalEnd(builder):
    return builder.EndObject()

def End(builder):
    return OptionalEnd(builder)
