# automatically generated by the FlatBuffers compiler, do not modify

# namespace: onnx

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Graph(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Graph()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGraph(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Graph
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Graph
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Graph
    def Node(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from onnx.Node import Node
            obj = Node()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Graph
    def NodeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Graph
    def NodeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Graph
    def Initializer(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from onnx.Tensor import Tensor
            obj = Tensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Graph
    def InitializerLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Graph
    def InitializerIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Graph
    def SparseInitializer(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from onnx.SparseTensor import SparseTensor
            obj = SparseTensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Graph
    def SparseInitializerLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Graph
    def SparseInitializerIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Graph
    def Input(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from onnx.ValueInfo import ValueInfo
            obj = ValueInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Graph
    def InputLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Graph
    def InputIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Graph
    def Output(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from onnx.ValueInfo import ValueInfo
            obj = ValueInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Graph
    def OutputLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Graph
    def OutputIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Graph
    def ValueInfo(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from onnx.ValueInfo import ValueInfo
            obj = ValueInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Graph
    def ValueInfoLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Graph
    def ValueInfoIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # Graph
    def QuantizationAnnotation(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from onnx.TensorAnnotation import TensorAnnotation
            obj = TensorAnnotation()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Graph
    def QuantizationAnnotationLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Graph
    def QuantizationAnnotationIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # Graph
    def DocString(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Graph
    def MetadataProps(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from onnx.StringStringEntry import StringStringEntry
            obj = StringStringEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Graph
    def MetadataPropsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Graph
    def MetadataPropsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

def GraphStart(builder):
    builder.StartObject(10)

def Start(builder):
    GraphStart(builder)

def GraphAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    GraphAddName(builder, name)

def GraphAddNode(builder, node):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(node), 0)

def AddNode(builder, node):
    GraphAddNode(builder, node)

def GraphStartNodeVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNodeVector(builder, numElems):
    return GraphStartNodeVector(builder, numElems)

def GraphAddInitializer(builder, initializer):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(initializer), 0)

def AddInitializer(builder, initializer):
    GraphAddInitializer(builder, initializer)

def GraphStartInitializerVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartInitializerVector(builder, numElems):
    return GraphStartInitializerVector(builder, numElems)

def GraphAddSparseInitializer(builder, sparseInitializer):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(sparseInitializer), 0)

def AddSparseInitializer(builder, sparseInitializer):
    GraphAddSparseInitializer(builder, sparseInitializer)

def GraphStartSparseInitializerVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSparseInitializerVector(builder, numElems):
    return GraphStartSparseInitializerVector(builder, numElems)

def GraphAddInput(builder, input):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(input), 0)

def AddInput(builder, input):
    GraphAddInput(builder, input)

def GraphStartInputVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartInputVector(builder, numElems):
    return GraphStartInputVector(builder, numElems)

def GraphAddOutput(builder, output):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(output), 0)

def AddOutput(builder, output):
    GraphAddOutput(builder, output)

def GraphStartOutputVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOutputVector(builder, numElems):
    return GraphStartOutputVector(builder, numElems)

def GraphAddValueInfo(builder, valueInfo):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(valueInfo), 0)

def AddValueInfo(builder, valueInfo):
    GraphAddValueInfo(builder, valueInfo)

def GraphStartValueInfoVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartValueInfoVector(builder, numElems):
    return GraphStartValueInfoVector(builder, numElems)

def GraphAddQuantizationAnnotation(builder, quantizationAnnotation):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(quantizationAnnotation), 0)

def AddQuantizationAnnotation(builder, quantizationAnnotation):
    GraphAddQuantizationAnnotation(builder, quantizationAnnotation)

def GraphStartQuantizationAnnotationVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartQuantizationAnnotationVector(builder, numElems):
    return GraphStartQuantizationAnnotationVector(builder, numElems)

def GraphAddDocString(builder, docString):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(docString), 0)

def AddDocString(builder, docString):
    GraphAddDocString(builder, docString)

def GraphAddMetadataProps(builder, metadataProps):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(metadataProps), 0)

def AddMetadataProps(builder, metadataProps):
    GraphAddMetadataProps(builder, metadataProps)

def GraphStartMetadataPropsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMetadataPropsVector(builder, numElems):
    return GraphStartMetadataPropsVector(builder, numElems)

def GraphEnd(builder):
    return builder.EndObject()

def End(builder):
    return GraphEnd(builder)

import onnx.Node
import onnx.SparseTensor
import onnx.StringStringEntry
import onnx.Tensor
import onnx.TensorAnnotation
import onnx.ValueInfo
try:
    from typing import List
except:
    pass

class GraphT(object):

    # GraphT
    def __init__(self):
        self.name = None  # type: str
        self.node = None  # type: List[onnx.Node.NodeT]
        self.initializer = None  # type: List[onnx.Tensor.TensorT]
        self.sparseInitializer = None  # type: List[onnx.SparseTensor.SparseTensorT]
        self.input = None  # type: List[onnx.ValueInfo.ValueInfoT]
        self.output = None  # type: List[onnx.ValueInfo.ValueInfoT]
        self.valueInfo = None  # type: List[onnx.ValueInfo.ValueInfoT]
        self.quantizationAnnotation = None  # type: List[onnx.TensorAnnotation.TensorAnnotationT]
        self.docString = None  # type: str
        self.metadataProps = None  # type: List[onnx.StringStringEntry.StringStringEntryT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        graph = Graph()
        graph.Init(buf, pos)
        return cls.InitFromObj(graph)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, graph):
        x = GraphT()
        x._UnPack(graph)
        return x

    # GraphT
    def _UnPack(self, graph):
        if graph is None:
            return
        self.name = graph.Name()
        if not graph.NodeIsNone():
            self.node = []
            for i in range(graph.NodeLength()):
                if graph.Node(i) is None:
                    self.node.append(None)
                else:
                    node_ = onnx.Node.NodeT.InitFromObj(graph.Node(i))
                    self.node.append(node_)
        if not graph.InitializerIsNone():
            self.initializer = []
            for i in range(graph.InitializerLength()):
                if graph.Initializer(i) is None:
                    self.initializer.append(None)
                else:
                    tensor_ = onnx.Tensor.TensorT.InitFromObj(graph.Initializer(i))
                    self.initializer.append(tensor_)
        if not graph.SparseInitializerIsNone():
            self.sparseInitializer = []
            for i in range(graph.SparseInitializerLength()):
                if graph.SparseInitializer(i) is None:
                    self.sparseInitializer.append(None)
                else:
                    sparseTensor_ = onnx.SparseTensor.SparseTensorT.InitFromObj(graph.SparseInitializer(i))
                    self.sparseInitializer.append(sparseTensor_)
        if not graph.InputIsNone():
            self.input = []
            for i in range(graph.InputLength()):
                if graph.Input(i) is None:
                    self.input.append(None)
                else:
                    valueInfo_ = onnx.ValueInfo.ValueInfoT.InitFromObj(graph.Input(i))
                    self.input.append(valueInfo_)
        if not graph.OutputIsNone():
            self.output = []
            for i in range(graph.OutputLength()):
                if graph.Output(i) is None:
                    self.output.append(None)
                else:
                    valueInfo_ = onnx.ValueInfo.ValueInfoT.InitFromObj(graph.Output(i))
                    self.output.append(valueInfo_)
        if not graph.ValueInfoIsNone():
            self.valueInfo = []
            for i in range(graph.ValueInfoLength()):
                if graph.ValueInfo(i) is None:
                    self.valueInfo.append(None)
                else:
                    valueInfo_ = onnx.ValueInfo.ValueInfoT.InitFromObj(graph.ValueInfo(i))
                    self.valueInfo.append(valueInfo_)
        if not graph.QuantizationAnnotationIsNone():
            self.quantizationAnnotation = []
            for i in range(graph.QuantizationAnnotationLength()):
                if graph.QuantizationAnnotation(i) is None:
                    self.quantizationAnnotation.append(None)
                else:
                    tensorAnnotation_ = onnx.TensorAnnotation.TensorAnnotationT.InitFromObj(graph.QuantizationAnnotation(i))
                    self.quantizationAnnotation.append(tensorAnnotation_)
        self.docString = graph.DocString()
        if not graph.MetadataPropsIsNone():
            self.metadataProps = []
            for i in range(graph.MetadataPropsLength()):
                if graph.MetadataProps(i) is None:
                    self.metadataProps.append(None)
                else:
                    stringStringEntry_ = onnx.StringStringEntry.StringStringEntryT.InitFromObj(graph.MetadataProps(i))
                    self.metadataProps.append(stringStringEntry_)

    # GraphT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        if self.node is not None:
            nodelist = []
            for i in range(len(self.node)):
                nodelist.append(self.node[i].Pack(builder))
            GraphStartNodeVector(builder, len(self.node))
            for i in reversed(range(len(self.node))):
                builder.PrependUOffsetTRelative(nodelist[i])
            node = builder.EndVector()
        if self.initializer is not None:
            initializerlist = []
            for i in range(len(self.initializer)):
                initializerlist.append(self.initializer[i].Pack(builder))
            GraphStartInitializerVector(builder, len(self.initializer))
            for i in reversed(range(len(self.initializer))):
                builder.PrependUOffsetTRelative(initializerlist[i])
            initializer = builder.EndVector()
        if self.sparseInitializer is not None:
            sparseInitializerlist = []
            for i in range(len(self.sparseInitializer)):
                sparseInitializerlist.append(self.sparseInitializer[i].Pack(builder))
            GraphStartSparseInitializerVector(builder, len(self.sparseInitializer))
            for i in reversed(range(len(self.sparseInitializer))):
                builder.PrependUOffsetTRelative(sparseInitializerlist[i])
            sparseInitializer = builder.EndVector()
        if self.input is not None:
            inputlist = []
            for i in range(len(self.input)):
                inputlist.append(self.input[i].Pack(builder))
            GraphStartInputVector(builder, len(self.input))
            for i in reversed(range(len(self.input))):
                builder.PrependUOffsetTRelative(inputlist[i])
            input = builder.EndVector()
        if self.output is not None:
            outputlist = []
            for i in range(len(self.output)):
                outputlist.append(self.output[i].Pack(builder))
            GraphStartOutputVector(builder, len(self.output))
            for i in reversed(range(len(self.output))):
                builder.PrependUOffsetTRelative(outputlist[i])
            output = builder.EndVector()
        if self.valueInfo is not None:
            valueInfolist = []
            for i in range(len(self.valueInfo)):
                valueInfolist.append(self.valueInfo[i].Pack(builder))
            GraphStartValueInfoVector(builder, len(self.valueInfo))
            for i in reversed(range(len(self.valueInfo))):
                builder.PrependUOffsetTRelative(valueInfolist[i])
            valueInfo = builder.EndVector()
        if self.quantizationAnnotation is not None:
            quantizationAnnotationlist = []
            for i in range(len(self.quantizationAnnotation)):
                quantizationAnnotationlist.append(self.quantizationAnnotation[i].Pack(builder))
            GraphStartQuantizationAnnotationVector(builder, len(self.quantizationAnnotation))
            for i in reversed(range(len(self.quantizationAnnotation))):
                builder.PrependUOffsetTRelative(quantizationAnnotationlist[i])
            quantizationAnnotation = builder.EndVector()
        if self.docString is not None:
            docString = builder.CreateString(self.docString)
        if self.metadataProps is not None:
            metadataPropslist = []
            for i in range(len(self.metadataProps)):
                metadataPropslist.append(self.metadataProps[i].Pack(builder))
            GraphStartMetadataPropsVector(builder, len(self.metadataProps))
            for i in reversed(range(len(self.metadataProps))):
                builder.PrependUOffsetTRelative(metadataPropslist[i])
            metadataProps = builder.EndVector()
        GraphStart(builder)
        if self.name is not None:
            GraphAddName(builder, name)
        if self.node is not None:
            GraphAddNode(builder, node)
        if self.initializer is not None:
            GraphAddInitializer(builder, initializer)
        if self.sparseInitializer is not None:
            GraphAddSparseInitializer(builder, sparseInitializer)
        if self.input is not None:
            GraphAddInput(builder, input)
        if self.output is not None:
            GraphAddOutput(builder, output)
        if self.valueInfo is not None:
            GraphAddValueInfo(builder, valueInfo)
        if self.quantizationAnnotation is not None:
            GraphAddQuantizationAnnotation(builder, quantizationAnnotation)
        if self.docString is not None:
            GraphAddDocString(builder, docString)
        if self.metadataProps is not None:
            GraphAddMetadataProps(builder, metadataProps)
        graph = GraphEnd(builder)
        return graph
