# automatically generated by the FlatBuffers compiler, do not modify

# namespace: onnx

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Node(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Node()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Node
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Node
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Node
    def OpType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Node
    def Domain(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Node
    def Overload(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Node
    def Input(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # Node
    def InputLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Node
    def InputIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Node
    def Output(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # Node
    def OutputLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Node
    def OutputIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Node
    def Attribute(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from onnx.Attribute import Attribute
            obj = Attribute()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Node
    def AttributeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Node
    def AttributeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # Node
    def DeviceConfigurations(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from onnx.NodeDeviceConfiguration import NodeDeviceConfiguration
            obj = NodeDeviceConfiguration()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Node
    def DeviceConfigurationsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Node
    def DeviceConfigurationsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # Node
    def DocString(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Node
    def MetadataProps(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from onnx.StringStringEntry import StringStringEntry
            obj = StringStringEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Node
    def MetadataPropsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Node
    def MetadataPropsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

def NodeStart(builder):
    builder.StartObject(10)

def Start(builder):
    NodeStart(builder)

def NodeAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    NodeAddName(builder, name)

def NodeAddOpType(builder, opType):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(opType), 0)

def AddOpType(builder, opType):
    NodeAddOpType(builder, opType)

def NodeAddDomain(builder, domain):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(domain), 0)

def AddDomain(builder, domain):
    NodeAddDomain(builder, domain)

def NodeAddOverload(builder, overload):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(overload), 0)

def AddOverload(builder, overload):
    NodeAddOverload(builder, overload)

def NodeAddInput(builder, input):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(input), 0)

def AddInput(builder, input):
    NodeAddInput(builder, input)

def NodeStartInputVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartInputVector(builder, numElems):
    return NodeStartInputVector(builder, numElems)

def NodeAddOutput(builder, output):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(output), 0)

def AddOutput(builder, output):
    NodeAddOutput(builder, output)

def NodeStartOutputVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOutputVector(builder, numElems):
    return NodeStartOutputVector(builder, numElems)

def NodeAddAttribute(builder, attribute):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(attribute), 0)

def AddAttribute(builder, attribute):
    NodeAddAttribute(builder, attribute)

def NodeStartAttributeVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAttributeVector(builder, numElems):
    return NodeStartAttributeVector(builder, numElems)

def NodeAddDeviceConfigurations(builder, deviceConfigurations):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(deviceConfigurations), 0)

def AddDeviceConfigurations(builder, deviceConfigurations):
    NodeAddDeviceConfigurations(builder, deviceConfigurations)

def NodeStartDeviceConfigurationsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDeviceConfigurationsVector(builder, numElems):
    return NodeStartDeviceConfigurationsVector(builder, numElems)

def NodeAddDocString(builder, docString):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(docString), 0)

def AddDocString(builder, docString):
    NodeAddDocString(builder, docString)

def NodeAddMetadataProps(builder, metadataProps):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(metadataProps), 0)

def AddMetadataProps(builder, metadataProps):
    NodeAddMetadataProps(builder, metadataProps)

def NodeStartMetadataPropsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMetadataPropsVector(builder, numElems):
    return NodeStartMetadataPropsVector(builder, numElems)

def NodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return NodeEnd(builder)

import onnx.Attribute
import onnx.NodeDeviceConfiguration
import onnx.StringStringEntry
try:
    from typing import List
except:
    pass

class NodeT(object):

    # NodeT
    def __init__(self):
        self.name = None  # type: str
        self.opType = None  # type: str
        self.domain = None  # type: str
        self.overload = None  # type: str
        self.input = None  # type: List[str]
        self.output = None  # type: List[str]
        self.attribute = None  # type: List[onnx.Attribute.AttributeT]
        self.deviceConfigurations = None  # type: List[onnx.NodeDeviceConfiguration.NodeDeviceConfigurationT]
        self.docString = None  # type: str
        self.metadataProps = None  # type: List[onnx.StringStringEntry.StringStringEntryT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        node = Node()
        node.Init(buf, pos)
        return cls.InitFromObj(node)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, node):
        x = NodeT()
        x._UnPack(node)
        return x

    # NodeT
    def _UnPack(self, node):
        if node is None:
            return
        self.name = node.Name()
        self.opType = node.OpType()
        self.domain = node.Domain()
        self.overload = node.Overload()
        if not node.InputIsNone():
            self.input = []
            for i in range(node.InputLength()):
                self.input.append(node.Input(i))
        if not node.OutputIsNone():
            self.output = []
            for i in range(node.OutputLength()):
                self.output.append(node.Output(i))
        if not node.AttributeIsNone():
            self.attribute = []
            for i in range(node.AttributeLength()):
                if node.Attribute(i) is None:
                    self.attribute.append(None)
                else:
                    attribute_ = onnx.Attribute.AttributeT.InitFromObj(node.Attribute(i))
                    self.attribute.append(attribute_)
        if not node.DeviceConfigurationsIsNone():
            self.deviceConfigurations = []
            for i in range(node.DeviceConfigurationsLength()):
                if node.DeviceConfigurations(i) is None:
                    self.deviceConfigurations.append(None)
                else:
                    nodeDeviceConfiguration_ = onnx.NodeDeviceConfiguration.NodeDeviceConfigurationT.InitFromObj(node.DeviceConfigurations(i))
                    self.deviceConfigurations.append(nodeDeviceConfiguration_)
        self.docString = node.DocString()
        if not node.MetadataPropsIsNone():
            self.metadataProps = []
            for i in range(node.MetadataPropsLength()):
                if node.MetadataProps(i) is None:
                    self.metadataProps.append(None)
                else:
                    stringStringEntry_ = onnx.StringStringEntry.StringStringEntryT.InitFromObj(node.MetadataProps(i))
                    self.metadataProps.append(stringStringEntry_)

    # NodeT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        if self.opType is not None:
            opType = builder.CreateString(self.opType)
        if self.domain is not None:
            domain = builder.CreateString(self.domain)
        if self.overload is not None:
            overload = builder.CreateString(self.overload)
        if self.input is not None:
            inputlist = []
            for i in range(len(self.input)):
                inputlist.append(builder.CreateString(self.input[i]))
            NodeStartInputVector(builder, len(self.input))
            for i in reversed(range(len(self.input))):
                builder.PrependUOffsetTRelative(inputlist[i])
            input = builder.EndVector()
        if self.output is not None:
            outputlist = []
            for i in range(len(self.output)):
                outputlist.append(builder.CreateString(self.output[i]))
            NodeStartOutputVector(builder, len(self.output))
            for i in reversed(range(len(self.output))):
                builder.PrependUOffsetTRelative(outputlist[i])
            output = builder.EndVector()
        if self.attribute is not None:
            attributelist = []
            for i in range(len(self.attribute)):
                attributelist.append(self.attribute[i].Pack(builder))
            NodeStartAttributeVector(builder, len(self.attribute))
            for i in reversed(range(len(self.attribute))):
                builder.PrependUOffsetTRelative(attributelist[i])
            attribute = builder.EndVector()
        if self.deviceConfigurations is not None:
            deviceConfigurationslist = []
            for i in range(len(self.deviceConfigurations)):
                deviceConfigurationslist.append(self.deviceConfigurations[i].Pack(builder))
            NodeStartDeviceConfigurationsVector(builder, len(self.deviceConfigurations))
            for i in reversed(range(len(self.deviceConfigurations))):
                builder.PrependUOffsetTRelative(deviceConfigurationslist[i])
            deviceConfigurations = builder.EndVector()
        if self.docString is not None:
            docString = builder.CreateString(self.docString)
        if self.metadataProps is not None:
            metadataPropslist = []
            for i in range(len(self.metadataProps)):
                metadataPropslist.append(self.metadataProps[i].Pack(builder))
            NodeStartMetadataPropsVector(builder, len(self.metadataProps))
            for i in reversed(range(len(self.metadataProps))):
                builder.PrependUOffsetTRelative(metadataPropslist[i])
            metadataProps = builder.EndVector()
        NodeStart(builder)
        if self.name is not None:
            NodeAddName(builder, name)
        if self.opType is not None:
            NodeAddOpType(builder, opType)
        if self.domain is not None:
            NodeAddDomain(builder, domain)
        if self.overload is not None:
            NodeAddOverload(builder, overload)
        if self.input is not None:
            NodeAddInput(builder, input)
        if self.output is not None:
            NodeAddOutput(builder, output)
        if self.attribute is not None:
            NodeAddAttribute(builder, attribute)
        if self.deviceConfigurations is not None:
            NodeAddDeviceConfigurations(builder, deviceConfigurations)
        if self.docString is not None:
            NodeAddDocString(builder, docString)
        if self.metadataProps is not None:
            NodeAddMetadataProps(builder, metadataProps)
        node = NodeEnd(builder)
        return node
