# automatically generated by the FlatBuffers compiler, do not modify

# namespace: onnx

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OptionalType(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OptionalType()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOptionalType(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OptionalType
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OptionalType
    def ElemTypeType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # OptionalType
    def ElemType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def OptionalTypeStart(builder):
    builder.StartObject(2)

def Start(builder):
    OptionalTypeStart(builder)

def OptionalTypeAddElemTypeType(builder, elemTypeType):
    builder.PrependUint8Slot(0, elemTypeType, 0)

def AddElemTypeType(builder, elemTypeType):
    OptionalTypeAddElemTypeType(builder, elemTypeType)

def OptionalTypeAddElemType(builder, elemType):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(elemType), 0)

def AddElemType(builder, elemType):
    OptionalTypeAddElemType(builder, elemType)

def OptionalTypeEnd(builder):
    return builder.EndObject()

def End(builder):
    return OptionalTypeEnd(builder)
