# automatically generated by the FlatBuffers compiler, do not modify

# namespace: onnx

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SequenceType(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SequenceType()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSequenceType(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SequenceType
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SequenceType
    def ElemTypeType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # SequenceType
    def ElemType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def SequenceTypeStart(builder):
    builder.StartObject(2)

def Start(builder):
    SequenceTypeStart(builder)

def SequenceTypeAddElemTypeType(builder, elemTypeType):
    builder.PrependUint8Slot(0, elemTypeType, 0)

def AddElemTypeType(builder, elemTypeType):
    SequenceTypeAddElemTypeType(builder, elemTypeType)

def SequenceTypeAddElemType(builder, elemType):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(elemType), 0)

def AddElemType(builder, elemType):
    SequenceTypeAddElemType(builder, elemType)

def SequenceTypeEnd(builder):
    return builder.EndObject()

def End(builder):
    return SequenceTypeEnd(builder)

import onnx.MapType
import onnx.OptionalType
import onnx.SparseTensorType
import onnx.TensorType
import onnx.ValueType
try:
    from typing import Union
except:
    pass

class SequenceTypeT(object):

    # SequenceTypeT
    def __init__(self):
        self.elemTypeType = 0  # type: int
        self.elemType = None  # type: Union[None, onnx.TensorType.TensorTypeT, onnx.SequenceType.SequenceTypeT, onnx.MapType.MapTypeT, onnx.OptionalType.OptionalTypeT, onnx.SparseTensorType.SparseTensorTypeT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        sequenceType = SequenceType()
        sequenceType.Init(buf, pos)
        return cls.InitFromObj(sequenceType)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, sequenceType):
        x = SequenceTypeT()
        x._UnPack(sequenceType)
        return x

    # SequenceTypeT
    def _UnPack(self, sequenceType):
        if sequenceType is None:
            return
        self.elemTypeType = sequenceType.ElemTypeType()
        self.elemType = onnx.ValueType.ValueTypeCreator(self.elemTypeType, sequenceType.ElemType())

    # SequenceTypeT
    def Pack(self, builder):
        if self.elemType is not None:
            elemType = self.elemType.Pack(builder)
        SequenceTypeStart(builder)
        SequenceTypeAddElemTypeType(builder, self.elemTypeType)
        if self.elemType is not None:
            SequenceTypeAddElemType(builder, elemType)
        sequenceType = SequenceTypeEnd(builder)
        return sequenceType
