# automatically generated by the FlatBuffers compiler, do not modify

# namespace: onnx

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SparseTensorType(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SparseTensorType()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSparseTensorType(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SparseTensorType
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SparseTensorType
    def ElemType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SparseTensorType
    def Shape(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from onnx.Shape import Shape
            obj = Shape()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SparseTensorTypeStart(builder):
    builder.StartObject(2)

def Start(builder):
    SparseTensorTypeStart(builder)

def SparseTensorTypeAddElemType(builder, elemType):
    builder.PrependInt32Slot(0, elemType, 0)

def AddElemType(builder, elemType):
    SparseTensorTypeAddElemType(builder, elemType)

def SparseTensorTypeAddShape(builder, shape):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(shape), 0)

def AddShape(builder, shape):
    SparseTensorTypeAddShape(builder, shape)

def SparseTensorTypeEnd(builder):
    return builder.EndObject()

def End(builder):
    return SparseTensorTypeEnd(builder)

import onnx.Shape
try:
    from typing import Optional
except:
    pass

class SparseTensorTypeT(object):

    # SparseTensorTypeT
    def __init__(self):
        self.elemType = 0  # type: int
        self.shape = None  # type: Optional[onnx.Shape.ShapeT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        sparseTensorType = SparseTensorType()
        sparseTensorType.Init(buf, pos)
        return cls.InitFromObj(sparseTensorType)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, sparseTensorType):
        x = SparseTensorTypeT()
        x._UnPack(sparseTensorType)
        return x

    # SparseTensorTypeT
    def _UnPack(self, sparseTensorType):
        if sparseTensorType is None:
            return
        self.elemType = sparseTensorType.ElemType()
        if sparseTensorType.Shape() is not None:
            self.shape = onnx.Shape.ShapeT.InitFromObj(sparseTensorType.Shape())

    # SparseTensorTypeT
    def Pack(self, builder):
        if self.shape is not None:
            shape = self.shape.Pack(builder)
        SparseTensorTypeStart(builder)
        SparseTensorTypeAddElemType(builder, self.elemType)
        if self.shape is not None:
            SparseTensorTypeAddShape(builder, shape)
        sparseTensorType = SparseTensorTypeEnd(builder)
        return sparseTensorType
