# automatically generated by the FlatBuffers compiler, do not modify

# namespace: onnx

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TrainingInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrainingInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrainingInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrainingInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrainingInfo
    def Initialization(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from onnx.Graph import Graph
            obj = Graph()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrainingInfo
    def Algorithm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from onnx.Graph import Graph
            obj = Graph()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrainingInfo
    def InitializationBinding(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from onnx.StringStringEntry import StringStringEntry
            obj = StringStringEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrainingInfo
    def InitializationBindingLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TrainingInfo
    def InitializationBindingIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # TrainingInfo
    def UpdateBinding(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from onnx.StringStringEntry import StringStringEntry
            obj = StringStringEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrainingInfo
    def UpdateBindingLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TrainingInfo
    def UpdateBindingIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def TrainingInfoStart(builder):
    builder.StartObject(4)

def Start(builder):
    TrainingInfoStart(builder)

def TrainingInfoAddInitialization(builder, initialization):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(initialization), 0)

def AddInitialization(builder, initialization):
    TrainingInfoAddInitialization(builder, initialization)

def TrainingInfoAddAlgorithm(builder, algorithm):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(algorithm), 0)

def AddAlgorithm(builder, algorithm):
    TrainingInfoAddAlgorithm(builder, algorithm)

def TrainingInfoAddInitializationBinding(builder, initializationBinding):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(initializationBinding), 0)

def AddInitializationBinding(builder, initializationBinding):
    TrainingInfoAddInitializationBinding(builder, initializationBinding)

def TrainingInfoStartInitializationBindingVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartInitializationBindingVector(builder, numElems):
    return TrainingInfoStartInitializationBindingVector(builder, numElems)

def TrainingInfoAddUpdateBinding(builder, updateBinding):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(updateBinding), 0)

def AddUpdateBinding(builder, updateBinding):
    TrainingInfoAddUpdateBinding(builder, updateBinding)

def TrainingInfoStartUpdateBindingVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartUpdateBindingVector(builder, numElems):
    return TrainingInfoStartUpdateBindingVector(builder, numElems)

def TrainingInfoEnd(builder):
    return builder.EndObject()

def End(builder):
    return TrainingInfoEnd(builder)
