# automatically generated by the FlatBuffers compiler, do not modify

# namespace: onnx

class ValueType(object):
    NONE = 0
    tensor_type = 1
    sequence_type = 2
    map_type = 3
    optional_type = 4
    sparse_tensor_type = 5
